services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest@sha256:bb570eb45c2994eaf32da783cc098b3d51d1095b73ec92919863d73d0a9eaafb
    ports:
      - "9411:9411"

  # Collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    command: [ "--config=/etc/otel-collector-config-demo.yaml" ]
    volumes:
      - ./otel-collector-config-demo.yaml:/etc/otel-collector-config-demo.yaml
    ports:
      - "4317:4317"   # otlp grpc receiver
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

networks:
  default:
    external:
      name: supertokens-core_default
