receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317

exporters:
  debug:
    # verbosity of the logging export: detailed, normal, basic
    verbosity: detailed

  otlphttp:
    compression: gzip
    endpoint: https://api.axiom.co
    headers:
      authorization: Bearer xaat-f8acc4ee-2d2c-4b14-9cb5-73ecee1f1f3e
      x-axiom-dataset: otel-st-integration-dev

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s


service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp ]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [ debug, otlphttp ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp ]

