name: Release
on:
  workflow_run:
    workflows: ["Unit Tests", "Publish Dev Docker Image"]
    branches: '**' # TODO: change to x.y
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The Run Tests workflow passed'
