name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    tags:
      - "(dev-)?v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test-inmemory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 15.0.1
          distribution: zulu
      - name: Checkout supertokens-root
        run: cd ../ && git clone https://github.com/supertokens/supertokens-root.git
      - name: Load Modules
        run: cd ../supertokens-root && echo "core,${{ github.ref_name }}\nplugin-interface,master\nsqlite-plugin,master" > modules.txt && ./loadModules
