name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    tags:
      - "(dev-)?v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test-inmemory:
    name: Unit Tests (In-Memory)
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 15.0.1
        uses: actions/setup-java@v2
        with:
          java-version: 15.0.1
          distribution: zulu
      - uses: actions/checkout@v2
        with:
          repository: supertokens/supertokens-root
          path: ./supertokens-root
          ref: master
      - uses: actions/checkout@v2
        with:
          path: ./supertokens-root/supertokens-core
      - uses: actions/checkout@v2
        with:
          repository: supertokens/supertokens-plugin-interface
          path: ./supertokens-root/supertokens-plugin-interface
          ref: 7.1
      - name: Load Modules
        run: ./loadModules
      - name: Setup test env
        run: ./utils/setupTestEnv --local
      - name: Run tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
          include_passed: true
